// Italian Verbs Telegram Bot - Vercel webhook style

// Store verbs in memory
const verbs = [
  { id: 1, italian: "andare", english: "to go" },
  { id: 2, italian: "avere", english: "to have" },
  { id: 3, italian: "essere", english: "to be" },
  { id: 4, italian: "fare", english: "to do / to make" },
  { id: 5, italian: "dire", english: "to say / to tell" },
  { id: 6, italian: "potere", english: "can / to be able to" },
  { id: 7, italian: "volere", english: "to want" },
  { id: 8, italian: "sapere", english: "to know (facts, how to)" },
  { id: 9, italian: "vedere", english: "to see" },
  { id: 10, italian: "dare", english: "to give" },
  { id: 11, italian: "parlare", english: "to speak / to talk" },
  { id: 12, italian: "trovare", english: "to find" },
  { id: 13, italian: "lasciare", english: "to leave" },
  { id: 14, italian: "prendere", english: "to take" },
  { id: 15, italian: "arrivare", english: "to arrive" },
  { id: 16, italian: "pensare", english: "to think" },
  { id: 17, italian: "conoscere", english: "to know (people, places)" },
  { id: 18, italian: "mettere", english: "to put / to place" },
  { id: 19, italian: "passare", english: "to pass / to spend (time)" },
  { id: 20, italian: "portare", english: "to bring / to carry" },
  { id: 21, italian: "tornare", english: "to return / to come back" },
  { id: 22, italian: "sentire", english: "to hear / to feel" },
  { id: 23, italian: "mangiare", english: "to eat" },
  { id: 24, italian: "bere", english: "to drink" },
  { id: 25, italian: "dormire", english: "to sleep" },
  { id: 26, italian: "vivere", english: "to live" },
  { id: 27, italian: "aprire", english: "to open" },
  { id: 28, italian: "chiudere", english: "to close" },
  { id: 29, italian: "lavorare", english: "to work" },
  { id: 30, italian: "studiare", english: "to study" },
  { id: 31, italian: "imparare", english: "to learn" },
  { id: 32, italian: "insegnare", english: "to teach" },
  { id: 33, italian: "comprare", english: "to buy" },
  { id: 34, italian: "vendere", english: "to sell" },
  { id: 35, italian: "pagare", english: "to pay" },
  { id: 36, italian: "cucinare", english: "to cook" },
  { id: 37, italian: "tagliare", english: "to cut" },
  { id: 38, italian: "lavare", english: "to wash" },
  { id: 39, italian: "aiutare", english: "to help" },
  { id: 40, italian: "usare", english: "to use" },
  { id: 41, italian: "camminare", english: "to walk" },
  { id: 42, italian: "correre", english: "to run" },
  { id: 43, italian: "guidare", english: "to drive" },
  { id: 44, italian: "viaggiare", english: "to travel" },
  { id: 45, italian: "salire", english: "to go up / to get on" },
  { id: 46, italian: "scendere", english: "to go down / to get off" },
  { id: 47, italian: "entrare", english: "to enter" },
  { id: 48, italian: "uscire", english: "to go out" },
  { id: 49, italian: "partire", english: "to leave / to depart" },
  { id: 50, italian: "fermare", english: "to stop" },
  { id: 51, italian: "amare", english: "to love" },
  { id: 52, italian: "odiare", english: "to hate" },
  { id: 53, italian: "piacere", english: "to like / to please" },
  { id: 54, italian: "desiderare", english: "to desire" },
  { id: 55, italian: "ricordare", english: "to remember" },
  { id: 56, italian: "dimenticare", english: "to forget" },
  { id: 57, italian: "credere", english: "to believe" },
  { id: 58, italian: "sperare", english: "to hope" },
  { id: 59, italian: "temere", english: "to fear" },
  { id: 60, italian: "preoccuparsi", english: "to worry" },
  { id: 61, italian: "chiedere", english: "to ask" },
  { id: 62, italian: "rispondere", english: "to answer" },
  { id: 63, italian: "raccontare", english: "to tell / to narrate" },
  { id: 64, italian: "spiegare", english: "to explain" },
  { id: 65, italian: "discutere", english: "to discuss" },
  { id: 66, italian: "chiamare", english: "to call" },
  { id: 67, italian: "telefonare", english: "to telephone" },
  { id: 68, italian: "invitare", english: "to invite" },
  { id: 69, italian: "salutare", english: "to greet" },
  { id: 70, italian: "gridare", english: "to shout" },
  { id: 71, italian: "pulire", english: "to clean" },
  { id: 72, italian: "buttare", english: "to throw away" },
  { id: 73, italian: "riparare", english: "to repair" },
  { id: 74, italian: "costruire", english: "to build" },
  { id: 75, italian: "cambiare", english: "to change" },
  { id: 76, italian: "vestire", english: "to dress" },
  { id: 77, italian: "spogliarsi", english: "to undress" },
  { id: 78, italian: "svegliarsi", english: "to wake up" },
  { id: 79, italian: "addormentarsi", english: "to fall asleep" },
  { id: 80, italian: "preparare", english: "to prepare" },
  { id: 81, italian: "piovere", english: "to rain" },
  { id: 82, italian: "nevicare", english: "to snow" },
  { id: 83, italian: "gelare", english: "to freeze" },
  { id: 84, italian: "bruciare", english: "to burn" },
  { id: 85, italian: "crescere", english: "to grow" },
  { id: 86, italian: "fiorire", english: "to bloom" },
  { id: 87, italian: "cadere", english: "to fall" },
  { id: 88, italian: "girare", english: "to turn" },
  { id: 89, italian: "volare", english: "to fly" },
  { id: 90, italian: "nuotare", english: "to swim" },
  { id: 91, italian: "respirare", english: "to breathe" },
  { id: 92, italian: "tossire", english: "to cough" },
  { id: 93, italian: "starnutire", english: "to sneeze" },
  { id: 94, italian: "guarire", english: "to heal" },
  { id: 95, italian: "ferire", english: "to injure" },
  { id: 96, italian: "ammalarsi", english: "to get sick" },
  { id: 97, italian: "curare", english: "to treat" },
  { id: 98, italian: "allenarsi", english: "to train" },
  { id: 99, italian: "muovere", english: "to move" },
  { id: 100, italian: "saltare", english: "to jump" },
  { id: 101, italian: "cercare", english: "to look for" },
  { id: 102, italian: "ottenere", english: "to obtain" },
  { id: 103, italian: "guadagnare", english: "to earn" },
  { id: 104, italian: "spendere", english: "to spend (money)" },
  { id: 105, italian: "risparmiare", english: "to save (money)" },
  { id: 106, italian: "firmare", english: "to sign" },
  { id: 107, italian: "inviare", english: "to send" },
  { id: 108, italian: "ricevere", english: "to receive" },
  { id: 109, italian: "consegnare", english: "to deliver" },
  { id: 110, italian: "organizzare", english: "to organize" },
  { id: 111, italian: "ballare", english: "to dance" },
  { id: 112, italian: "cantare", english: "to sing" },
  { id: 113, italian: "suonare", english: "to play (instrument)" },
  { id: 114, italian: "giocare", english: "to play (games, sports)" },
  { id: 115, italian: "visitare", english: "to visit" },
  { id: 116, italian: "fotografare", english: "to photograph" },
  { id: 117, italian: "guardare", english: "to watch / to look at" },
  { id: 118, italian: "leggere", english: "to read" },
  { id: 119, italian: "scrivere", english: "to write" },
  { id: 120, italian: "dipingere", english: "to paint" },
  { id: 121, italian: "disegnare", english: "to draw" },
  { id: 122, italian: "recitare", english: "to act / to perform" },
  { id: 123, italian: "ascoltare", english: "to listen" },
  { id: 124, italian: "tradurre", english: "to translate" },
  { id: 125, italian: "filmare", english: "to film" },
  { id: 126, italian: "scolpire", english: "to sculpt" },
  { id: 127, italian: "comporre", english: "to compose (music)" },
  { id: 128, italian: "creare", english: "to create" },
  { id: 129, italian: "digitare", english: "to type" },
  { id: 130, italian: "cliccare", english: "to click" },
  { id: 131, italian: "stampare", english: "to print" },
  { id: 132, italian: "salvare", english: "to save (file)" },
  { id: 133, italian: "caricare", english: "to upload / to charge" },
  { id: 134, italian: "scaricare", english: "to download" },
  { id: 135, italian: "installare", english: "to install" },
  { id: 136, italian: "programmare", english: "to program" },
  { id: 137, italian: "registrare", english: "to record" },
  { id: 138, italian: "navigare", english: "to surf / to browse" },
  { id: 139, italian: "ordinare", english: "to order" },
  { id: 140, italian: "scegliere", english: "to choose" },
  { id: 141, italian: "misurare", english: "to measure" },
  { id: 142, italian: "pesare", english: "to weigh" },
  { id: 143, italian: "costare", english: "to cost" },
  { id: 144, italian: "restituire", english: "to return (an item)" },
  { id: 145, italian: "contrattare", english: "to bargain" },
  { id: 146, italian: "incassare", english: "to cash in" },
  { id: 147, italian: "investire", english: "to invest" },
  { id: 148, italian: "bollire", english: "to boil" },
  { id: 149, italian: "friggere", english: "to fry" },
  { id: 150, italian: "arrostire", english: "to roast" },
  { id: 151, italian: "cuocere", english: "to cook / to bake" },
  { id: 152, italian: "mescolare", english: "to mix" },
  { id: 153, italian: "pelare", english: "to peel" },
  { id: 154, italian: "sbucciare", english: "to peel (fruit)" },
  { id: 155, italian: "condire", english: "to season" },
  { id: 156, italian: "assaggiare", english: "to taste" },
  { id: 157, italian: "spazzare", english: "to sweep" },
  { id: 158, italian: "strofinare", english: "to scrub" },
  { id: 159, italian: "lucidare", english: "to polish" },
  { id: 160, italian: "spolverare", english: "to dust" },
  { id: 161, italian: "igienizzare", english: "to sanitize" },
  { id: 162, italian: "disinfettare", english: "to disinfect" },
  { id: 163, italian: "riordinare", english: "to rearrange" },
  { id: 164, italian: "piantare", english: "to plant" },
  { id: 165, italian: "annaffiare", english: "to water (plants)" },
  { id: 166, italian: "raccogliere", english: "to gather / to pick" },
  { id: 167, italian: "seminare", english: "to sow" },
  { id: 168, italian: "potare", english: "to prune" },
  { id: 169, italian: "irrigare", english: "to irrigate" },
  { id: 170, italian: "coltivare", english: "to cultivate" },
  { id: 171, italian: "innaffiare", english: "to water" },
  { id: 172, italian: "falciare", english: "to mow" },
  { id: 173, italian: "scavare", english: "to dig" },
  { id: 174, italian: "tuonare", english: "to thunder" },
  { id: 175, italian: "lampeggiare", english: "to flash (lightning)" },
  { id: 176, italian: "grandinare", english: "to hail" },
  { id: 177, italian: "ghiacciare", english: "to ice over" },
  { id: 178, italian: "soleggiare", english: "to be sunny" },
  { id: 179, italian: "oscurare", english: "to darken" },
  { id: 180, italian: "rischiarare", english: "to brighten" },
  { id: 181, italian: "vaccinare", english: "to vaccinate" },
  { id: 182, italian: "operare", english: "to operate" },
  { id: 183, italian: "bendare", english: "to bandage" },
  { id: 184, italian: "diagnosticare", english: "to diagnose" },
  { id: 185, italian: "prescrivere", english: "to prescribe" },
  { id: 186, italian: "analizzare", english: "to analyze" },
  { id: 187, italian: "controllare", english: "to check" },
  { id: 188, italian: "arrampicare", english: "to climb" },
  { id: 189, italian: "pedalare", english: "to pedal" },
  { id: 190, italian: "sciare", english: "to ski" },
  { id: 191, italian: "pattinare", english: "to skate" },
  { id: 192, italian: "tirare", english: "to throw / to pull" },
  { id: 193, italian: "calciare", english: "to kick" },
  { id: 194, italian: "allenare", english: "to train" },
  { id: 195, italian: "imbarcare", english: "to board" },
  { id: 196, italian: "sbarcare", english: "to disembark" },
  { id: 197, italian: "attraccare", english: "to dock" },
  { id: 198, italian: "prenotare", english: "to book" },
  { id: 199, italian: "apprezzare", english: "to appreciate" },
  { id: 200, italian: "ringraziare", english: "to thank" },
  { id: 201, italian: "perdonare", english: "to forgive" },
  { id: 202, italian: "pentirsi", english: "to regret" },
  { id: 203, italian: "rallegrarsi", english: "to rejoice" },
  { id: 204, italian: "arrabbiarsi", english: "to get angry" },
  { id: 205, italian: "deprimersi", english: "to get depressed" },
  { id: 206, italian: "capire", english: "to understand" },
  { id: 207, italian: "riflettere", english: "to reflect" },
  { id: 208, italian: "immaginare", english: "to imagine" },
  { id: 209, italian: "sognare", english: "to dream" },
  { id: 210, italian: "valutare", english: "to evaluate" },
  { id: 211, italian: "affermare", english: "to state" },
  { id: 212, italian: "avvisare", english: "to warn" },
  { id: 213, italian: "suggerire", english: "to suggest" },
  { id: 214, italian: "riposare", english: "to rest" },
  { id: 215, italian: "vestirsi", english: "to get dressed" },
  { id: 216, italian: "pettinarsi", english: "to comb hair" },
  { id: 217, italian: "truccarsi", english: "to put on makeup" },
  { id: 218, italian: "archiviare", english: "to file" },
  { id: 219, italian: "copiare", english: "to copy" },
  { id: 220, italian: "allegare", english: "to attach" },
  { id: 221, italian: "pianificare", english: "to plan" },
  { id: 222, italian: "aspettare", english: "to wait" },
  { id: 223, italian: "restare", english: "to stay" },
  { id: 224, italian: "durare", english: "to last" },
  { id: 225, italian: "cominciare", english: "to begin" },
  { id: 226, italian: "finire", english: "to finish" },
  { id: 227, italian: "continuare", english: "to continue" },
  { id: 228, italian: "interrompere", english: "to interrupt" },
  { id: 229, italian: "migliorare", english: "to improve" },
  { id: 230, italian: "peggiorare", english: "to worsen" },
  { id: 231, italian: "scegliere", english: "to choose" },
  { id: 232, italian: "decidere", english: "to decide" },
  { id: 233, italian: "giudicare", english: "to judge" },
  { id: 234, italian: "votare", english: "to vote" },
  { id: 235, italian: "eleggere", english: "to elect" },
  { id: 236, italian: "dichiarare", english: "to declare" },
  { id: 237, italian: "approvare", english: "to approve" },
  { id: 238, italian: "rifiutare", english: "to refuse" },
  { id: 239, italian: "accettare", english: "to accept" },
  { id: 240, italian: "confermare", english: "to confirm" },
  { id: 241, italian: "bastare", english: "to be enough" },
  { id: 242, italian: "servire", english: "to serve" },
  { id: 243, italian: "mancare", english: "to miss / to lack" },
  { id: 244, italian: "succedere", english: "to happen" },
  { id: 245, italian: "sembrare", english: "to seem" },
  { id: 246, italian: "apparire", english: "to appear" },
  { id: 247, italian: "scomparire", english: "to disappear" },
  { id: 248, italian: "diventare", english: "to become" },
  { id: 249, italian: "restare", english: "to remain" },
  { id: 250, italian: "appartenere", english: "to belong" },
  { id: 251, italian: "presentare", english: "to present" },
  { id: 252, italian: "rappresentare", english: "to represent" },
  { id: 253, italian: "proteggere", english: "to protect" },
  { id: 254, italian: "difendere", english: "to defend" },
  { id: 255, italian: "attaccare", english: "to attack" },
  { id: 256, italian: "colpire", english: "to hit" },
  { id: 257, italian: "rompere", english: "to break" },
  { id: 258, italian: "distruggere", english: "to destroy" },
  { id: 259, italian: "inventare", english: "to invent" },
  { id: 260, italian: "scoprire", english: "to discover" },
  { id: 261, italian: "perdere", english: "to lose" },
  { id: 262, italian: "prendere in prestito", english: "to borrow" },
  { id: 263, italian: "rubare", english: "to steal" },
  { id: 264, italian: "bloccare", english: "to block" },
  { id: 265, italian: "sbloccare", english: "to unblock" },
  { id: 266, italian: "attivare", english: "to activate" },
  { id: 267, italian: "disattivare", english: "to deactivate" },
  { id: 268, italian: "accendere", english: "to turn on" },
  { id: 269, italian: "spegnere", english: "to turn off" },
  { id: 270, italian: "inserire", english: "to insert" },
  { id: 271, italian: "estrarre", english: "to extract" },
  { id: 272, italian: "riempire", english: "to fill" },
  { id: 273, italian: "svuotare", english: "to empty" },
  { id: 274, italian: "separare", english: "to separate" },
  { id: 275, italian: "unire", english: "to unite" },
  { id: 276, italian: "dividere", english: "to divide" },
  { id: 277, italian: "aumentare", english: "to increase" },
  { id: 278, italian: "diminuire", english: "to decrease" },
  { id: 279, italian: "ridurre", english: "to reduce" },
  { id: 280, italian: "iniziare", english: "to start" },
  { id: 281, italian: "terminare", english: "to end" },
  { id: 282, italian: "completare", english: "to complete" },
  { id: 283, italian: "cancellare", english: "to delete" },
  { id: 284, italian: "spostare", english: "to shift" },
  { id: 285, italian: "esplorare", english: "to explore" },
  { id: 286, italian: "parcheggiare", english: "to park" },
  { id: 287, italian: "rimanere", english: "to remain" },
  { id: 288, italian: "marciare", english: "to march" },
  { id: 289, italian: "spingere", english: "to push" },
  { id: 290, italian: "trascinare", english: "to drag" },
  { id: 291, italian: "sollevare", english: "to lift" },
  { id: 292, italian: "abbassare", english: "to lower" },
  { id: 293, italian: "saltellare", english: "to hop" },
  { id: 294, italian: "capovolgere", english: "to flip over" },
  { id: 295, italian: "ruotare", english: "to rotate" },
  { id: 296, italian: "avvicinare", english: "to bring closer" },
  { id: 297, italian: "allontanare", english: "to move away" },
  { id: 298, italian: "attraversare", english: "to cross" },
  { id: 299, italian: "percorrere", english: "to travel through" },
  { id: 300, italian: "oltrepassare", english: "to go beyond" },
  { id: 301, italian: "inseguiere", english: "to chase" },
  { id: 302, italian: "fuggire", english: "to escape" },
  { id: 303, italian: "nascondere", english: "to hide" },
  { id: 304, italian: "mostrare", english: "to show" },
  { id: 305, italian: "indicare", english: "to indicate" },
  { id: 306, italian: "puntare", english: "to point" },
  { id: 307, italian: "dirigere", english: "to direct" },
  { id: 308, italian: "gestire", english: "to manage" },
  { id: 309, italian: "comandare", english: "to command" },
  { id: 310, italian: "replicare", english: "to reply again" },
  { id: 311, italian: "obiettare", english: "to object" },
  { id: 312, italian: "negare", english: "to deny" },
  { id: 313, italian: "permettere", english: "to allow" },
  { id: 314, italian: "vietare", english: "to forbid" },
  { id: 315, italian: "obbligare", english: "to oblige" },
  { id: 316, italian: "costringere", english: "to force" },
  { id: 317, italian: "liberare", english: "to free" },
  { id: 318, italian: "imprigionare", english: "to imprison" },
  { id: 319, italian: "arrestare", english: "to arrest" },
  { id: 320, italian: "memorizzare", english: "to memorize" },
  { id: 321, italian: "esercitarsi", english: "to practice" },
  { id: 322, italian: "provare", english: "to try" },
  { id: 323, italian: "tentare", english: "to attempt" },
  { id: 324, italian: "sperimentare", english: "to experiment" },
  { id: 325, italian: "verificare", english: "to verify" },
  { id: 326, italian: "testare", english: "to test" },
  { id: 327, italian: "correggere", english: "to correct" },
  { id: 328, italian: "sbagliare", english: "to make a mistake" },
  { id: 329, italian: "fallire", english: "to fail" },
  { id: 330, italian: "riuscire", english: "to succeed" },
  { id: 331, italian: "vincere", english: "to win" },
  { id: 332, italian: "pareggiare", english: "to draw (game)" },
  { id: 333, italian: "competere", english: "to compete" },
  { id: 334, italian: "combattere", english: "to fight" },
  { id: 335, italian: "litigare", english: "to argue" },
  { id: 336, italian: "collaborare", english: "to collaborate" },
  { id: 337, italian: "aiutare", english: "to help" },
  { id: 338, italian: "sostenere", english: "to support" },
  { id: 339, italian: "appoggiare", english: "to back up" },
  { id: 340, italian: "condividere", english: "to share" },
  { id: 341, italian: "mischiare", english: "to mix up" },
  { id: 342, italian: "confondere", english: "to confuse" },
  { id: 343, italian: "sistemare", english: "to fix / arrange" },
  { id: 344, italian: "prevedere", english: "to foresee" },
  { id: 345, italian: "anticipare", english: "to anticipate" },
  { id: 346, italian: "ritardare", english: "to delay" },
  { id: 347, italian: "rimandare", english: "to postpone" },
  { id: 348, italian: "sostituire", english: "to replace" },
  { id: 349, italian: "scambiare", english: "to exchange" },
  { id: 350, italian: "adattare", english: "to adapt" },
  { id: 351, italian: "modificare", english: "to modify" },
  { id: 352, italian: "trasformare", english: "to transform" },
  { id: 353, italian: "sviluppare", english: "to develop" },
  { id: 354, italian: "estendere", english: "to extend" },
  { id: 355, italian: "restringere", english: "to narrow" },
  { id: 356, italian: "espandere", english: "to expand" },
  { id: 357, italian: "concentrare", english: "to concentrate" },
  { id: 358, italian: "disperdere", english: "to scatter" },
  { id: 359, italian: "accumulare", english: "to accumulate" },
  { id: 360, italian: "distribuire", english: "to distribute" },
  { id: 361, italian: "fornire", english: "to provide" },
  { id: 362, italian: "mandare", english: "to send" },
  { id: 363, italian: "spedire", english: "to ship" },
  { id: 364, italian: "trasportare", english: "to transport" },
  { id: 365, italian: "acquisire", english: "to acquire" },
  { id: 366, italian: "commerciare", english: "to trade" },
  { id: 367, italian: "affittare", english: "to rent" },
  { id: 368, italian: "noleggiare", english: "to hire/rent" },
  { id: 369, italian: "misurare", english: "to measure" },
  { id: 370, italian: "pesare", english: "to weigh" },
  { id: 371, italian: "contare", english: "to count" },
  { id: 372, italian: "calcolare", english: "to calculate" },
  { id: 373, italian: "sommare", english: "to add" },
  { id: 374, italian: "sottrarre", english: "to subtract" },
  { id: 375, italian: "moltiplicare", english: "to multiply" },
  { id: 376, italian: "dividere", english: "to divide" },
  { id: 377, italian: "confrontare", english: "to compare" },
  { id: 378, italian: "valutare", english: "to evaluate" },
  { id: 379, italian: "stimare", english: "to estimate" },
  { id: 380, italian: "apprezzare", english: "to appreciate" },
  { id: 381, italian: "criticare", english: "to criticize" },
  { id: 382, italian: "elogiare", english: "to praise" },
  { id: 383, italian: "incoraggiare", english: "to encourage" },
  { id: 384, italian: "consigliare", english: "to advise" },
  { id: 385, italian: "avvertire", english: "to warn" },
  { id: 386, italian: "minacciare", english: "to threaten" },
  { id: 387, italian: "promettere", english: "to promise" },
  { id: 388, italian: "garantire", english: "to guarantee" },
  { id: 389, italian: "assicurare", english: "to insure/assure" },
  { id: 390, italian: "rischiare", english: "to risk" },
  { id: 391, italian: "evitare", english: "to avoid" },
  { id: 392, italian: "prevenire", english: "to prevent" },
  { id: 393, italian: "proteggere", english: "to protect" },
  { id: 394, italian: "difendere", english: "to defend" },
  { id: 395, italian: "attaccare", english: "to attack" },
  { id: 396, italian: "resistere", english: "to resist" },
  { id: 397, italian: "arrendersi", english: "to surrender" },
  { id: 398, italian: "negoziare", english: "to negotiate" },
  { id: 399, italian: "concordare", english: "to agree" },
  { id: 400, italian: "disaccordare", english: "to disagree" },
  { id: 401, italian: "discutere", english: "to discuss" },
  { id: 402, italian: "dibattere", english: "to debate" },
  { id: 403, italian: "persuadere", english: "to persuade" },
  { id: 404, italian: "convincere", english: "to convince" },
  { id: 405, italian: "insistere", english: "to insist" },
  { id: 406, italian: "esitare", english: "to hesitate" },
  { id: 407, italian: "decidere", english: "to decide" },
  { id: 408, italian: "scoprire", english: "to discover" },
  { id: 409, italian: "inventare", english: "to invent" },
  { id: 410, italian: "innovare", english: "to innovate" },
  { id: 411, italian: "migliorare", english: "to improve" },
  { id: 412, italian: "perfezionare", english: "to perfect" },
  { id: 413, italian: "peggiorare", english: "to worsen" },
  { id: 414, italian: "danneggiare", english: "to damage" },
  { id: 415, italian: "riparare", english: "to repair" },
  { id: 416, italian: "sostituire", english: "to replace" },
  { id: 417, italian: "modernizzare", english: "to modernize" },
  { id: 418, italian: "conservare", english: "to preserve" },
  { id: 419, italian: "cambiare", english: "to change" },
  { id: 420, italian: "trasformare", english: "to transform" },
  { id: 421, italian: "evolvere", english: "to evolve" },
  { id: 422, italian: "semplificare", english: "to simplify" },
  { id: 423, italian: "complicare", english: "to complicate" },
  { id: 424, italian: "organizzare", english: "to organize" },
  { id: 425, italian: "riorganizzare", english: "to reorganize" },
  { id: 426, italian: "pianificare", english: "to plan" },
  { id: 427, italian: "programmare", english: "to program" },
  { id: 428, italian: "preparare", english: "to prepare" },
  { id: 429, italian: "allenare", english: "to train" },
  { id: 430, italian: "esercitare", english: "to exercise" },
  { id: 431, italian: "praticare", english: "to practice" },
  { id: 432, italian: "insegnare", english: "to teach" },
  { id: 433, italian: "imparare", english: "to learn" },
  { id: 434, italian: "studiare", english: "to study" },
  { id: 435, italian: "leggere", english: "to read" },
  { id: 436, italian: "scrivere", english: "to write" },
  { id: 437, italian: "copiare", english: "to copy" },
  { id: 438, italian: "incollare", english: "to paste" },
  { id: 439, italian: "disegnare", english: "to draw" },
  { id: 440, italian: "dipingere", english: "to paint" },
  { id: 441, italian: "scolpire", english: "to sculpt" },
  { id: 442, italian: "fotografare", english: "to photograph" },
  { id: 443, italian: "filmare", english: "to film" },
  { id: 444, italian: "registrare", english: "to record" },
  { id: 445, italian: "riprodurre", english: "to reproduce" },
  { id: 446, italian: "suonare", english: "to play (instrument)" },
  { id: 447, italian: "cantare", english: "to sing" },
  { id: 448, italian: "ballare", english: "to dance" },
  { id: 449, italian: "recitare", english: "to act" },
  { id: 450, italian: "rappresentare", english: "to represent" },
  { id: 451, italian: "esibire", english: "to perform" },
  { id: 452, italian: "competere", english: "to compete" },
  { id: 453, italian: "vincere", english: "to win" },
  { id: 454, italian: "perdere", english: "to lose" },
  { id: 455, italian: "pareggiare", english: "to tie/draw" },
  { id: 456, italian: "celebrare", english: "to celebrate" },
  { id: 457, italian: "festeggiare", english: "to party/celebrate" },
  { id: 458, italian: "congratularsi", english: "to congratulate" },
  { id: 459, italian: "ringraziare", english: "to thank" },
  { id: 460, italian: "salutare", english: "to greet" },
  { id: 461, italian: "presentare", english: "to introduce" },
  { id: 462, italian: "accompagnare", english: "to accompany" },
  { id: 463, italian: "seguire", english: "to follow" },
  { id: 464, italian: "guidare", english: "to guide" },
  { id: 465, italian: "condurre", english: "to lead" },
  { id: 466, italian: "scortare", english: "to escort" },
  { id: 467, italian: "proteggere", english: "to protect" },
  { id: 468, italian: "difendere", english: "to defend" },
  { id: 469, italian: "aiutare", english: "to help" },
  { id: 470, italian: "soccorrere", english: "to rescue" },
  { id: 471, italian: "curare", english: "to care for" },
  { id: 472, italian: "guarire", english: "to heal" },
  { id: 473, italian: "vaccinare", english: "to vaccinate" },
  { id: 474, italian: "operare", english: "to operate" },
  { id: 475, italian: "trapiantare", english: "to transplant" },
  { id: 476, italian: "diagnosticare", english: "to diagnose" },
  { id: 477, italian: "prescrivere", english: "to prescribe" },
  { id: 478, italian: "medicare", english: "to medicate" },
  { id: 479, italian: "disinfettare", english: "to disinfect" },
  { id: 480, italian: "sterilizzare", english: "to sterilize" },
  { id: 481, italian: "rianimare", english: "to resuscitate" },
  { id: 482, italian: "salvare", english: "to save" },
  { id: 483, italian: "morire", english: "to die" },
  { id: 484, italian: "seppellire", english: "to bury" },
  { id: 485, italian: "cremare", english: "to cremate" },
  { id: 486, italian: "piangere", english: "to cry" },
  { id: 487, italian: "ridere", english: "to laugh" },
  { id: 488, italian: "sorridere", english: "to smile" },
  { id: 489, italian: "sbadigliare", english: "to yawn" },
  { id: 490, italian: "sussurrare", english: "to whisper" },
  { id: 491, italian: "urlare", english: "to shout" },
  { id: 492, italian: "gridare", english: "to yell" },
  { id: 493, italian: "bisbigliare", english: "to murmur" },
  { id: 494, italian: "cantare", english: "to sing" },
  { id: 495, italian: "fischiare", english: "to whistle" },
  { id: 496, italian: "applaudire", english: "to applaud" },
  { id: 497, italian: "incoraggiare", english: "to encourage" },
  { id: 498, italian: "consolare", english: "to comfort" },
  { id: 499, italian: "confessare", english: "to confess" },
  { id: 500, italian: "promettere", english: "to promise" },
];

// Store user progress in memory
const userProgress = new Map();

// Main webhook handler
export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(200).send("Bot running");
  }

  const { message } = req.body;
  const chatId = message?.chat?.id;
  const text = message?.text?.trim();

  if (!chatId || !text) return res.status(200).end();

  // START command
  if (text === "/start" || text === "/restart") {
    userProgress.set(chatId, 0);
    await askQuestion(chatId);
    return res.status(200).end();
  }

  // ANSWER handling
  let currentIndex = userProgress.get(chatId) ?? 0;

  if (currentIndex < verbs.length) {
    const verb = verbs[currentIndex];
    const correctAnswer = verb.english.toLowerCase();
    const userAnswer = text.toLowerCase();

    if (userAnswer === correctAnswer) {
      await sendMessage(
        chatId,
        `✅ Correct! **${verb.italian}** means **${verb.english}**.`
      );
    } else {
      await sendMessage(
        chatId,
        `❌ Not quite. **${verb.italian}** means **${verb.english}**.`
      );
    }

    // Move to next question
    userProgress.set(chatId, currentIndex + 1);
    await askQuestion(chatId);
  } else {
    await sendMessage(
      chatId,
      "🎉 Congratulations! You've completed all 500 verbs!"
    );
    userProgress.set(chatId, 0);
  }

  res.status(200).end();
}

// Ask next question
async function askQuestion(chatId) {
  const index = userProgress.get(chatId) ?? 0;
  if (index < verbs.length) {
    const verb = verbs[index];
    await sendMessage(
      chatId,
      `(${verb.id}/${verbs.length}) What does **${verb.italian}** mean?`
    );
  }
}

// Send message to Telegram
async function sendMessage(chatId, text) {
  await fetch(
    `https://api.telegram.org/bot${process.env.BOT_TOKEN}/sendMessage`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text,
        parse_mode: "Markdown",
      }),
    }
  );
}
